project:
  type: website
  output-dir: docs

website:
  title: "US Census Income Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: sources.qmd
        text: Sources
      - href: model.qmd
        text: Model

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true